events {
    worker_connections 1024; # Nombre maximum de connexions par processus
}

http {
    upstream iris-apis {
    server mlops-iris-api:8000;
    }
    # Définition de notre serveur virtuel
    server {
        listen 80;
        server_name localhost; # Nom de domaine ou IP que ce bloc serveur gère

        # Toutes les requêtes qui commencent par /predict/ seront traitées ici
        location /predict {
            proxy_pass http://iris-apis;
            # proxy_pass: Redirige la requête vers le groupe upstream
            
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }
    
}